apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-best-effort-deployment
  labels:
    app: spring-boot-best-effort
  namespace: spring-boot-best-effort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-best-effort
  template:
    metadata:
      labels:
        app: spring-boot-best-effort
    spec:
      containers:
      - name: spring-boot-best-effort
        image: kubecuddle.jfrog.io/default-docker-local/swagger-java-app:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 5
          timeoutSeconds: 5      
          successThreshold: 1  
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

