apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-burstable-deployment
  labels:
    app: spring-boot-burstable
  namespace: spring-boot-burstable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-burstable
  template:
    metadata:
      labels:
        app: spring-boot-burstable
    spec:
      containers:
      - name: spring-boot-burstable
        image: kubecuddle.jfrog.io/default-docker-local/swagger-java-app:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 5
          timeoutSeconds: 5      
          successThreshold: 1  
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
           cpu: 500m 
           memory: 500Mi
          requests:
            cpu: 200m
            memory: 256Mi

